### ISSUE TITLE
docker vanallenlab/moalmanac:0.4.3_v.2023-02-02  run error 

### ISSUE THREAD

**Issue by ArsFc** [vanallenlab/moalmanac#11]
maf file include KARS:c.38G>A:p.G13D muation  , when run moalmanac.py ,it print 
Traceback (most recent call last):
  File "/moalmanac/moalmanac.py", line 357, in <module>
    main(patient_dict, inputs_dict, output_directory)
  File "/moalmanac/moalmanac.py", line 230, in main
    plot=plot_preclinical
  File "/moalmanac/moalmanac.py", line 124, in process_preclinical_efficacy
    efficacy_dictionary = investigator.SensitivityDictionary.create(dbs, dataframe)
  File "/moalmanac/investigator.py", line 142, in create
    mapped = list(mappings[sensitive_therapy][cls.gdsc])
KeyError: 'Sotorasib'

**Comment by brendanreardon** [comment]
Hi @ArsFc, thank you for identifying this bug! We believe that this has been resolved in [this pull request](https://github.com/vanallenlab/moalmanac/pull/12) that we were scheduled to merge today anyway, we were able to sneak in the bug fix. Can you try pulling the latest main branch on GitHub or with [vanallenlab/moalmanac:0.4.5_v.2023-02-02](https://hub.docker.com/r/vanallenlab/moalmanac/tags) from Docker to see if this problem persists for you?

**Comment by ArsFc** [comment]
> Hi @ArsFc, thank you for identifying this bug! We believe that this has been resolved in [this pull request](https://github.com/vanallenlab/moalmanac/pull/12) that we were scheduled to merge today anyway, we were able to sneak in the bug fix. Can you try pulling the latest main branch on GitHub or with [vanallenlab/moalmanac:0.4.5_v.2023-02-02](https://hub.docker.com/r/vanallenlab/moalmanac/tags) from Docker to see if this problem persists for you?

Thanks for the timely reply, form docker the problem is solved ...

**Comment by brendanreardon** [comment]
Great! We're very glad to hear that. Don't hesitate to reach out if you notice anything else off.
